services:
    mc-server:
        container_name: mc-server
        image: itzg/minecraft-server
        ports:
            - "25565:25565"
            - "25575:25575"
        volumes:
            - ${DATA_PATH}:/data
        environment:
            EULA: "TRUE"
            ENABLE_RCON: "TRUE"
            RCON_PASSWORD: ${RCON_PASSWORD}
            RCON_PORT: 25575
