services:
    mc-server:
        container_name: mc-server
        image: itzg/minecraft-server
        ports:
            - "25565:25565"
            - "25575:25575"
        networks:
            - mc-server-backend
        volumes:
            - ${DATA_PATH}:/data
        environment:
            EULA: "TRUE"
            ENABLE_RCON: "TRUE"
            RCON_PASSWORD: ${RCON_PASSWORD}
            RCON_PORT: 25575
    mc-server-monitor:
        container_name: mc-server-monitor
        image: cosmtrek/air # hot reloading
        working_dir: /app/
        networks:
            - mc-server-backend
        ports:
            - "8080:8080"
        depends_on:
            mc-server:
                condition: service_healthy
                restart: true
        environment:
            RCON_ADDRESS: ${RCON_ADDRESS}
            RCON_PASSWORD: ${RCON_PASSWORD}
            SERVER_ADDRESS: ${SERVER_ADDRESS}
        volumes:
            - ./:/app/
networks:
    mc-server-backend:
        driver: bridge
